name: Run C# Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build Mandelbrot -c Release
        working-directory: ./c#
      - name: Run test
        working-directory: ./c#
        run: |
          cd Mandelbrot/Mandelbrot/
          dotnet bin/Release/netcoreapp3.1/Mandelbrot.dll &
          pid=$!
          sleep 1
          cd ../../../sh
          ./monitor.sh $(pgrep dotnet) > monitoring.out &
          sh c-sharp-index.sh
          cat monitoring.out
