name: Run Go Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Prepare packages
        working-directory: ./go
        run: |
          go mod download
      - name: Build
        working-directory: ./go
        run: |
          go build ./cmd/mandelbrot
      - name: Prepare directory
        working-directory: ./go
        run: |
          mkdir db
      - name: Run test
        working-directory: ./go
        run: |
          set -x
          ./mandelbrot & $(pid=$! && echo "$pid" && cd ../sh && sh index.sh && ps -p $pid -o %cpu,%mem)
          set +x
