name: Run Go Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            memory_profiler
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Prepare packages
        working-directory: ./go
        run: |
          go mod download
      - name: Build
        working-directory: ./go
        run: |
          go build ./cmd/mandelbrot
      - name: Prepare directory
        working-directory: ./go
        run: |
          mkdir db
      - name: Run test
        working-directory: ./go
        run: |
          $(mprof run ./mandelbrot) & $(cd ../sh && sh index.sh && mprof plot)
