name: Continuous Integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Prepare packages
        working-directory: ./go
        run: |
          go mod download
      - name: Build
        working-directory: ./go
        run: |
          go build ./cmd/mandelbrot
      - name: Run test
        working-directory: ./go
        run: |
          ./main & $(cd ../sh && sh index.sh)
