name: Run Java Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Maven install
        working-directory: ./java/spring-mandelbrot
        run: |
          mvn install
      - name: Run test
        working-directory: ./java/spring-mandelbrot/target
        run: |
          java -jar mandelbrot-1.0-SNAPSHOT.jar &
          echo "Started Spring Application"
          cd ../../../sh
          echo "Changed Directory"
          sh java-index.sh
          echo "Kill java"
          killall java
          echo "exit"
          exit
