name: Run Python Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            click
            Flask
            itsdangerous
            Jinja2
            MarkupSafe
            uuid
            waitress
            Werkzeug
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: python index.py
        working-directory: ./python

      - name: Run test
        working-directory: ./python
        run: |
          cd ../sh && sh index.sh
